### CREATE
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "user": "user",
    "senha":"senha",
    "funcao": "funcao"

}

### GET ONE
GET http://localhost:3000/api/user/66229235656ea44cbec2fb6c

### GET ALL
GET http://localhost:3000/api/user

###
DELETE http://localhost:3000/api/user/66226d841df8e00816e77034

### UPDATE
PUT http://localhost:3000/api/user/66226d841df8e00816e77034
Content-Type: application/json

{
    "user": "teste",
    "senha": "senha de teste",
    "funcao": "funcao" 
}

### LOGIN
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "user": "teste",
    "senha": "senha de teste"
}
